name = "SSR-create-defender"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19ca380a9699d9afc7686776cf5e541d23716f86175e629c904af81af3b690d4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
