name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3b2fc3d25d8252bcc9f15104c088d79d845dfd4866843fe9403453ffae0e93c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
