name = "SSR-create-defender"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9658e089bdc546164cc528c1cfb4406c2695a5959abc059c53a18dfbf6b3f70b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
